packages:
  - ./html-hunter
  - ./hunt-client
  - ./hunt-crawler
  - ./hunt-fst
  - ./hunt-searchengine
  - ./hunt-server
  - ./hunt-server-cli
extra-deps:
  - data-r-tree-0.0.5.0
  - data-stringmap-1.0.1.1
  - murmur-hash-0.1.0.8
  - ekg-core-0.1.0.4
  - hxt-xpath-9.1.2.2
  - hxt-cache-9.1.0.1
  - docopt-0.7.0.2
resolver: lts-2.13


