packages:
  - ./html-hunter
  - ./hunt-client
  - ./hunt-crawler
  - ./hunt-searchengine
  - ./hunt-api
  - ./hunt-cli
  - ./hunt-server
  - ./hunt-test/data/jokes
  - ./fox
extra-deps:
  - aeson-1.0.2.1
  - data-r-tree-0.0.5.0
  - data-stringmap-1.0.1.1
  - dictionary-1.3.0.0
  - http-api-data-0.3.2
  - hxt-cache-9.1.0.1
  - hxt-xpath-9.1.2.2
  - servant-0.9.1.1
  - servant-client-0.9.1.1
  - servant-server-0.9.1.1
  - store-0.3
  - store-core-0.3
  - containers-0.5.9.1
  - directory-1.3.0.0
resolver: nightly-2016-08-06
